### ISSUE TITLE
Brightness Shortcuts v1.8

### ISSUE THREAD

**Issue by istjgeek** [LumingYin/TouchBarDisabler#10]
Brightness controls aren't working for me. (Mute, Vol+, Vol- are working fine)

- Restarted laptop, didn't help.
- I'm on 10.13.1

**Comment by dddddddddddddddddddddddddddd** [comment]
Same here, for both 1.7 and 1.8.

**Comment by LumingYin** [comment]
Looking into it.

**Comment by dddddddddddddddddddddddddddd** [comment]
👍

**Comment by LumingYin** [comment]
In version 1.9, the brightness control should now behave as intended.

**[Download TouchBarDisabler 1.9 for macOS High Sierra](https://github.com/LumingYin/TouchBarDisabler/releases/download/1.9/TouchBarDisabler-1.9.dmg)**
