### ISSUE TITLE
Brightness not working

### ISSUE THREAD

**Issue by mmille24** [LumingYin/TouchBarDisabler#13]
I've upgraded to 'High Sierra.' I then launched the touchbar disabler. It worked as normal.

However, control + 1/2 for brightness NO longer does anything.  Control + 9/0 DOES still control the volume.

**Comment by LumingYin** [comment]
Download the latest build:
https://github.com/LumingYin/TouchBarDisabler/releases/download/1.9/TouchBarDisabler-1.9.dmg

**Comment by mmille24** [comment]
Thanks! That worked. I'm noticing the brightness does change, but I don't actually see the level like I do for the volume.  Did that change?

**Comment by LumingYin** [comment]
Yes - this is normal behavior under macOS High Sierra.

**Comment by dmk255** [comment]
I am also running version 1.9 but ctrl+1 / ctrl+2  does not change the display brightness
