### ISSUE TITLE
Problems with Microsoft Word

### ISSUE THREAD

**Issue by mmille24** [LumingYin/TouchBarDisabler#23]
When I attempt to 'Save As' a document in Microsoft Word, it automatically closes the 'save as' screen immediately. When I disable the 'Touch Bar disabler' it allows me to select and save as normal.

I've noticed this in within the Preferences> iCloud option as well. I try to enter my password there and it closes the window immediately.

**Comment by realThinhIT** [comment]
I had this issue before, had to enable Touch Bar before saving documents because (any) Save dialog wouldn't show up.

**Comment by LumingYin** [comment]
Seems like this is already fixed by Apple in the latest public beta of macOS Mojave, hence closing.
