### ISSUE TITLE
Brightness changes via key combos should persist through sleep/wake

### ISSUE THREAD

**Issue by kevinflo** [LumingYin/TouchBarDisabler#5]
Device: 15" MBP 2017 with radeon 560

The brightness the screen is at when the user turns on touchbar disabler seems to be sticky between computer sleep, whereas subsequent brightness changes are not

Repro:
1. Restart computer with touchbar disabler off
2. Decrease screen brightness with the touch bar to very very dim
3. Turn on touchbar disabler
4. hit ctrl+2 many times until screen is at full brightness
5. close laptop
6. open laptop

expected: screen is still at full brightness
actual: screen reverts back to very very dim

**Comment by LumingYin** [comment]
This issue should be resolved with the 1.7 release. Download the update and see if it's fixed for you :)
