### ISSUE TITLE
Version 1.8 Doesn't Work

### ISSUE THREAD

**Issue by dddddddddddddddddddddddddddd** [LumingYin/TouchBarDisabler#9]
I installed version 1.8 within minutes of its release.

Every time I enabled or disabled it, however, I had to enter my Mac's password.

Plus, the Touch Bar remained disabled, even after I enabled it.

I downgraded back to version 1.7, and it works again.

**Comment by LumingYin** [comment]
Are you running macOS Sierra (10.12) or macOS High Sierra (10.13)?

**Comment by dddddddddddddddddddddddddddd** [comment]
macOS High Sierra (10.13)

**Comment by LumingYin** [comment]
Thanks! I'm looking into it.

**Comment by dddddddddddddddddddddddddddd** [comment]
👍

**Comment by LumingYin** [comment]
In version 1.9:
- you only need to authenticate the app with your password once
- brightness controls now behave as intended

**[Download TouchBarDisabler 1.9 for macOS High Sierra](https://github.com/LumingYin/TouchBarDisabler/releases/download/1.9/TouchBarDisabler-1.9.dmg)**
